spring:
  datasource:
    url: jdbc:mysql://SERVER:PORT/DB_NAME?allowPublicKeyRetrieval=true&useSSL=false
    username: USERNAME
    password: PASSWORD
  mail:
    host: smtp.gmail.com
    port: PORT
    username: EMAIL
    password: PASSWORD
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connection timeout: 5000
          timeout: 5000
          write timeout: 5000
    send:
      cron: 0 0 0 * * ?

app:
  api-key: API_KEY
